name: CI
on: [push]

jobs: 
    teste:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SonarCloud scan
              uses: SonarSource/sonarqube-scan-action@v4.1.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
